### PR TITLE
Add support for all log commands on the previous container for a pod (-p)

### LINKED ISSUE #17: No aliases for `kubectl logs -p <podName>`
I often use this command to get logs of the previous container in a pod (e.g. in the event of pod crash) - but it's not in the aliases list, could something be added?

### PR DESCRIPTION
**Pull request by henricook**
Fixes #17.

### CODE REVIEW

**Comment by henricook** [comment]
Sorry will fix the CLA from home this weekend! I just raised this patch in the editor and won't be in front of a non-work machine where i can sign in to personal things for a few days

**Comment by henricook** [comment]
Aha! Good to go!

**Comment by ahmetb** [comment]
looks like your indentation is off, and you didn't run the generate script with the new .kubectl_aliases file. :)

**Comment by henricook** [comment]
Oh gahhhhd I didn't read the contributors.md, the shame. Will fix

**Comment by henricook** [comment]
@ahmetb Updated - sorry about that, how's it look now?

**Review by ahmetb — APPROVED** [review]

**Comment by henricook** [comment]
Sweet, thanks!

**Pull request merged**
