### PR TITLE
"kubectl get all" command support

### PR DESCRIPTION
**Pull request by developer-guy**

### CODE REVIEW

**Comment by ahmetb** [comment]
@developer-guy have you actually executed the script? I have a suspicion that the output will not match the edits you (I assume) made to the file manually. I expect ksysga to be generated with the changes you made.

**Comment by developer-guy** [comment]
yes , i already executed this script and i got an expected result for command. @ahmetb

**Comment by developer-guy** [comment]
> @developer-guy have you actually executed the script? I have a suspicion that the output will not match the edits you (I assume) made to the file manually. I expect ksysga to be generated with the changes you made.

@ahmetb , i checked again the result of this script , it generated both of them :

alias kga='kubectl get all'   <br/>                                                                              alias ksysga='kubectl --namespace=kube-system get all'

how can i avoid to generate the second one for this script ?

**Comment by ahmetb** [comment]
Ksysga actually is useful. 
That said get all actually doesn’t get all. Thats’s why we have a krew plugin named “get-all” that actually gets all resources. So maybe this patch doesn’t achieve much.

**Comment by deepaksood619** [comment]
Why these `alias` are not added?

**Comment by ahmetb** [comment]
It’s explained above. Feel free to add this alias manually to your own fork. This generates only 2 aliases so doesn’t really need programmatic generation.

**Pull request closed without merging**
