### PR TITLE
Improve alias generation performance

### PR DESCRIPTION
**Pull request by LFrobeen**
This PR proposes the following changes:
 - Improve performance of the `combinations` function, allowing for generating aliases with more optional args in reasonable runtime,
 - Add checks and warnings if conflicts aliases are detected (helps identifying if newly added args would cause clashing aliases)
 - Allow `w` flag to be used in conjunction output format flags like `oyaml`, `ojson` and `owide`

The main motivation for the PR was addressing the performance of the `combinations` function which I've noticed to be prohibitively slow if more args are added. Many of the permutations generated by the `combinations` include incompatible flags which can be filtered out early to make the overall generation run faster.

Moreover, this PR adds a few more permutations of the `w`, `ojson`, `oyaml` and `owide` flags. Previously the incompatibility definitions on the `w` flag tried to prevent it being used with json, yaml and wide outputs. However, due to the way incompatibilities were evaluated (look-behind check) the script still emitted permutations where `w` was followed by `ojson` etc, but not the other way around. This PR makes the incompatibility check global (i.e. not only look-behind) and allows `w` to be used with output formats in any order.

### CODE REVIEW

**Comment by ahmetb** [comment]
This is superb, I've been hoping to optimize this but I rarely regenerate aliases so I never bothered.

**Comment by ahmetb** [comment]
> Allow watch flag to be used with json, yaml and wide flags f168a28

do you mind if we drop this commit? I think it increases alias count, hence the load time 35% for no good use case really.

**Comment by LFrobeen** [comment]
> > Allow watch flag to be used with json, yaml and wide flags [f168a28](https://github.com/ahmetb/kubectl-aliases/commit/f168a2821d1907672c53b5bf93a92b1d61cfaca1)
> 
> do you mind if we drop this commit? I think it increases alias count, hence the load time 35% for no good use case really.

Sure, no problem. One thing to note though is that this will remove any combinations of `w` with `ojson`, `oyaml` etc, whereas the original implementation allowed `w` followed by `ojson` (e.g. https://github.com/ahmetb/kubectl-aliases/blob/b2ee5dbd3d03717a596d69ee3f6dc6de8b140128/.kubectl_aliases#L335-L352). Please let me know if this behaviour was intended. If not, I could probably modify my code so that it preserves the original semantics of the look-behind incompatibility check. What are your thoughts on this @ahmetb?

**Comment by ahmetb** [comment]
No that wasn't intended I think.

**Comment by LFrobeen** [comment]
I've removed the commit in question (https://github.com/ahmetb/kubectl-aliases/commit/f168a2821d1907672c53b5bf93a92b1d61cfaca1). The new behaviour is that `w` won't be combined with any output formats in any order which reduces the total number of aliases by 459.

**Pull request merged**
