### PR TITLE
Add kpf/kpfn as port-forward alias shortcut.

### LINKED ISSUE #33: Consider `kpf` for kubectl port-forward
Port forward is used a lot in debugging Kubernetes workloads.

### PR DESCRIPTION
**Pull request by incfly**
fix https://github.com/ahmetb/kubectl-aliases/issues/33

### CODE REVIEW

**Comment by incfly** [comment]
@ahmetb PTAL, thanks.

**Comment by ahmetb** [comment]
You need to update the code buddy :)

**Comment by incfly** [comment]
Aha, will update. Didn't see a CI/CD test to fail, :)

**Comment by ahmetb** [comment]
Yeah there’s no cicd. I am the cicd.

**Comment by incfly** [comment]
Done.

**Comment by ahmetb** [comment]
Thank you. 🙏

**Comment by incfly** [comment]
np! I do feel a bit lost while looking at that python code, but now i can
get rid of my own `alias kpf` :)

**Pull request merged**
