### PR TITLE
Alias's uncovering fix

### PR DESCRIPTION
**Pull request by freele**

### CODE REVIEW

**Comment by freele** [comment]
@googlebot I signed it!

**Comment by ahmetb** [comment]
This looks good but I don't understand how it's any different. What's the issue here?

**Comment by freele** [comment]
All good, just misspells.  
before: `func kubectl(){` . 
after: `function kubectl() {` . 
both keyword and space between () { matter

**Comment by ahmetb** [comment]
In that case can we still keep it single line? If so, please make the change. 

Thanks for discovering this.

**Comment by freele** [comment]
fixed

**Review by ahmetb — APPROVED** [review]

**Pull request merged**
