### PR TITLE
Add aliases for PV and PVC resources

### PR DESCRIPTION
**Pull request by alinnow**

### CODE REVIEW

**Comment by alinnow** [comment]
I thought this wasn't an official Google project, as stated in the readme?

I don't have a Google account and am not willing to open one.

**Comment by ahmetb** [comment]
Google still owns the copyright since I work at Google.

We've had people add other resources ~~below~~ before. This increases the already large alias list even larger. I recommend you fork this project and maintain your own list (pretty easy).

**Comment by alinnow** [comment]
Alright, will do.

**Comment by alphabt** [comment]
@ahmetb I understand the desire to not balloon the combinations, but I manage PVC on a daily basis and PV/PVC are such integral components of K8s, I hope one day this tool supports them so I can adopt it and let it be a force multiplier to my team.

**Comment by ahmetb** [comment]
@iczman ok I'll accept this since it came up many times. Feel free to send another PR.

**Pull request closed without merging**
